# Generated by Django 5.1.5 on 2025-01-24 12:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name_plural': 'Cart Items'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name_plural': 'Order Details'},
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='profile/%Y/%m'),
        ),
    ]
